version: '3.8'

services:
  backend:
    build:
      target: development
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=true
      - RELOAD=true
      - LOG_LEVEL=DEBUG
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      target: development
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - /app/node_modules
    environment:
      - REACT_APP_ENV=development
      - CHOKIDAR_USEPOLLING=true
    command: npm start

  # Development database (SQLite)
  dev-db:
    image: alpine:latest
    container_name: chatbot-dev-db
    volumes:
      - ./data/dev.db:/data/dev.db
    command: tail -f /dev/null
    profiles:
      - development
