name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ChatBot/backend/requirements.txt
          pip install pytest pytest-asyncio flake8

      - name: Lint with flake8
        run: |
          flake8 ChatBot/backend/app

      - name: Install pytest-rerunfailures
        run: |
          pip install pytest-rerunfailures

      - name: Run tests
        run: |
          pytest ChatBot/backend/tests --cov=ChatBot/backend/app --cov-fail-under=80 --count=3 --reruns 2 --reruns-delay 5
